platform :ios, '5.1'
pod 'JSONKit',       '~> 1.4'
pod 'Reachability',  '~> 3.0.0'
pod 'NMPaginator', '~> 1.0.0'
pod 'SVProgressHUD'
pod 'SWRevealViewController'
pod 'SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage'